# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js and React app to Azure Web App - webappprod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: $GITHUB_SHA-npm

      - name: npm ci and build
        run: |
          cd webapp
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Copy build artifacts to root directory
        run: |
          mkdir -p webapp/build && cp -R webapp/build/* webapp/
          rm -rf webapp/build

      - name: Zip only necessary files
        run: zip webappprod.zip webapp/build/* -r
          echo "Artifact zipped successfully"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: webappprod.zip
          run: |
           echo "Artifact uploaded successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          run: |
           echo "Artifact downloaded successfully"

      - name: Unzip artifact
        run: unzip webappprod.zip

      - name: Print success message
        run: echo "Artifact unzipped successfully"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: 'service_principal'
          resourceManagerEndpoint: 'https://management.azure.com/'
          run: |
           echo "Logged in to Azure successfully"

      - name: Wait for 30 seconds to avoid SCM container restart
        run: sleep 30

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappprod'
          package: '${{ github.workspace }}/webappprod.zip'
